name: release zip

on:
  workflow_dispatch:

permissions:
  contents: write

jobs:
  release:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Create ZIP archive
        run: |
          zip -r SM-A356N_DFE.zip . -x "README.md" "LICENSE" ".git/*" ".github/*"

      - name: Create GitHub release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: "v1.0"
          name: "DFE v1.0 for SM-A356N"
          body: |
            Device: SM-A356N
            Version: v1.0

            Based on recovery zip flash method.

            Be sure to format /data after flashing this!
            If you encounter "Unmounting /data..." errors, reboot to recovery and try again.
          files: SM-A356N_DFE_v1.0.zip
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
